set(ARCANE_SOURCES
  AlinaGlobal.h
  AlinaUtils.cc
  Adapters.h
  AlinaLib.h
  AlinaLib.cc
  AlinaLibMPI.h
  AlinaLibMPI.cc
        AMG.h
  BlockCSRBackend.h
  BuiltinBackend.h
  HybridBuiltinBackend.h
  CudaBackend.h
  backend_detail_matrix_ops.h
  BackendInterface.h
  BlockCSRMatrix.h
  CSRMatrix.h
  Coarsening.h
  CoarseningRuntime.h
  DeflatedSolver.h
  DenseMatrixInverseImpl.h
  QRFactorizationImpl.h
  detail_sort_row.h
  SparseMatrixMatrixProduct.h
  EigenAdapter.h
  EigenBackend.h
        IO.h
  ios_saver.h
  make_block_solver.h
  PreconditionedSolver.h
  perf_counter_clock.h
  CPRDynamicRowSumPreconditioner.h
  CPRPreconditioner.h
  DummyPreconditioner.h
  PreconditionerRuntime.h
  SchurPressureCorrectionPreconditioner.h
  profiler.h
  relaxation_cusparse_ilu0.h
  ILUSolverImpl.h
  RelaxationRuntime.h
  RelaxationRuntime.cc
  Relaxation.h
  reorder_cuthill_mckee.h
  BiCGStabSolver.h
  FlexibleGMRESSolver.h
  ConjugateGradientSolver.h
  solver_detail_default_inner_product.h
  solver_detail_givens_rotations.h
  solver_eigen.h
  FlexibleGMRESSolver.h
  GMRESSolver.h
  IDRSSolver.h
  LooseGMRESSolver.h
  solver_precond_side.h
  PreconditionerOnlySolver.h
  RichardsonSolver.h
  SolverRuntime.h
  SkylineLUSolver.h
  util.h
        ValueTypeInterface.h
        ValueTypeComplex.h
        ValueTypeEigen.h
        StaticMatrix.h

  DistributedAMG.h
  DistributedCoarsening.h
  DistributedCoarseningRuntime.h
  DistributedCPRPreconditioner.h
  DistributedDirectSolverBase.h
  DistributedDirectSolverRuntime.h
  DistributedEigenSparseLUDirectSolver.h
  DistributedSkylineLUDirectSolver.h
  DistributedMatrix.h
  DistributedInnerProduct.h
  DistributedPreconditioner.h
  DistributedPreconditionedSolver.h
  DistributedRelaxation.h
  DistributedRelaxationRuntime.h
  DistributedSchurPressureCorrection.h
  DistributedSolver.h
  DistributedSolverRuntime.h
  DistributedSubDomainDeflation.h
  SimpleMatrixPartitioner.h
  ParmetisMatrixPartitioner.h
  MatrixPartitionerRuntime.h
  MatrixPartitionUtils.h
  mp_util.h
)
