set(ARCANE_SOURCES
  AlinaGlobal.h
  AlinaUtils.cc
  Adapters.h
  AlinaLib.h
  AlinaLib.cc
  AlinaLibMPI.h
  AlinaLibMPI.cc
  adapter_ublas.h
  AMG.h
  backend_block_crs.h
  backend_builtin.h
  backend_builtin_hybrid.h
  backend_cuda.h
  backend_detail_default_direct_solver.h
  backend_detail_matrix_ops.h
  backend_detail_mixing.h
  BackendInterface.h
  BlockCSRMatrix.h
  CSRMatrix.h
  coarsening.h
  coarsening_detail_galerkin.h
  coarsening_detail_scaled_galerkin.h
  coarsening_runtime.h
  deflated_solver.h
  detail_inverse.h
  detail_qr.h
  detail_sort_row.h
  detail_spgemm.h
  EigenAdapter.h
  EigenBackend.h
  EpetraAdapter.h
  IO.h
  ios_saver.h
  make_block_solver.h
  make_solver.h
  perf_counter_clock.h
  preconditioner_cpr_drs.h
  preconditioner_cpr.h
  preconditioner_dummy.h
  preconditioner_runtime.h
  preconditioner_schur_pressure_correction.h
  perf_counter_mpi_aggregator.h
  profiler.h
  relaxation_cusparse_ilu0.h
  relaxation_detail_ilu_solve.h
  RelaxationRuntime.h
  RelaxationRuntime.cc
  relaxation.h
  reorder_cuthill_mckee.h
  solver_bicgstab.h
  solver_bicgstabl.h
  solver_cg.h
  solver_detail_default_inner_product.h
  solver_detail_givens_rotations.h
  solver_eigen.h
  solver_fgmres.h
  solver_gmres.h
  solver_idrs.h
  solver_lgmres.h
  solver_precond_side.h
  solver_preonly.h
  solver_richardson.h
  solver_runtime.h
  solver_skyline_lu.h
  util.h
  value_type_backend_interface.h
  value_type_complex.h
  value_type_eigen.h
  value_type_static_matrix.h

  mpi/mp_amg.h
  mpi/mp_block_preconditioner.h
  mpi/mp_coarsening_aggregation.h
  mpi/mp_coarsening_pmis.h
  mpi/mp_coarsening_runtime.h
  mpi/mp_coarsening_smoothed_aggregation.h
  mpi/mp_cpr.h
  mpi/mp_direct_solve_eigen_splu.h
  mpi/mp_direct_solver_base.h
  mpi/mp_direct_solver_runtime.h
  mpi/mp_direct_solver_skyline_lu.h
  mpi/mp_distributed_matrix.h
  mpi/mp_inner_product.h
  mpi/mp_make_solver.h
  mpi/mp_partition_merge.h
  mpi/mp_partition_parmetis.h
  mpi/mp_partition_runtime.h
  mpi/mp_partition_util.h
  mpi/mp_preconditioner.h
  mpi/mp_relaxation_runtime.h
  mpi/mp_relaxation.h
  mpi/mp_schur_pressure_correction.h
  mpi/mp_solver.h
  mpi/mp_solver_runtime.h
  mpi/mp_subdomain_deflation.h
  mpi/mp_util.h
)
